catch grep exit status 1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,7 +18,9 @@ jobs:
     steps:
       - name: Install build dependencies
         run: |
-          pacman -Syu --needed --noconfirm ghc git unzip haskell-shake haskell-aeson-pretty cmake ninja fmt extra-cmake-modules fcitx5 boost opencc jdk17-openjdk python cabal-install check binutils
+          pacman -Syu --needed --noconfirm \
+            git ghc cabal-install haskell-shake haskell-aeson-pretty \
+            cmake extra-cmake-modules ninja fmt fcitx5 boost opencc jdk17-openjdk check
 
       - name: Fetch source code
         uses: actions/checkout@v4
@@ -47,12 +49,15 @@ jobs:
         shell: bash
         run: |
           shopt -s globstar nullglob
+          # https://stackoverflow.com/a/49627999
+          # "catch exit status 1" grep wrapper
+          c1grep() { grep "$@" || test $? = 1; }
           cd build
           for TARGET in $(<artifacts.txt)
           do
             for FILE in ./"$TARGET"/**/*.a
             do
-              STRINGS=$(strings --all --bytes=8 "$FILE" | grep prebuilder)
+              STRINGS=$(strings --all --bytes=8 "$FILE" | c1grep prebuilder | c1grep -v grep)
               if [ -n "${STRINGS}" ]
               then
                 echo -e "::warning:: Hardcoded path in '$FILE':\n$STRINGS"
